### ISSUE TITLE
CampaignManager is not defined error

### ISSUE THREAD

**Issue by aps2201** [google/cm-creatives-drive-uploader#3]
in cm.gs file the CampaignManager.* should be DoubleClickCampaigns.*

**Comment by mohabfekry** [comment]
Thanks for opening an issue. If you view the associated [appsscript.json](https://github.com/google/cm-creatives-drive-uploader/blob/ad3072e97cd0267c7de403f2c44281536fab7561/resources/appsscript.json#L13) file you will notice that the service for the CM360 API (scope "dfareporting") is defined as CampaignManager.
